spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/listenWang/SpringCloudConfig.git
          search-paths:
          username: 2631748820@qq.com
          password: 720027abc
server:
  port: 7001